site_name: Specify-DotNet
theme: readthedocs
markdown_extensions: [fenced_code]
pages:
- Home: index.md
- Features:
  - Overview: features-overview.md
- Using Specify:
  - Getting Started: getting-started.md
  - Configuration: configuration.md